#!/usr/bin/env python3
"""
Promote staged Wave Factory batches into canonical USDR folders.

Default mode is dry-run (validation + move plan only).
Use --apply to actually move files.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_STAGE = ROOT / "drafts" / "wave_factory"


def load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        raise ValueError(f"{path.relative_to(ROOT)} is empty")
    if not isinstance(data, dict):
        raise ValueError(f"{path.relative_to(ROOT)} root must be a mapping")
    return data


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_validators() -> dict[str, Draft202012Validator]:
    schema_root = ROOT / "schemas"
    return {
        "bridge": Draft202012Validator(load_yaml(schema_root / "bridge.yaml")),
        "unknown": Draft202012Validator(load_yaml(schema_root / "unknown.yaml")),
        "hypothesis": Draft202012Validator(load_yaml(schema_root / "hypothesis.yaml")),
    }


def validate_file(path: Path, kind: str, validator: Draft202012Validator) -> list[str]:
    errors: list[str] = []
    instance = load_yaml(path)
    for err in validator.iter_errors(instance):
        loc = "/".join(str(p) for p in err.absolute_path) or "(root)"
        errors.append(f"{path.relative_to(ROOT)} [{loc}]: {err.message}")

    record_id = str(instance.get("id") or "")
    if kind == "bridge" and not record_id.startswith("b-"):
        errors.append(f"{path.relative_to(ROOT)} [id]: bridge id must start with b-")
    if kind == "unknown" and not record_id.startswith("u-"):
        errors.append(f"{path.relative_to(ROOT)} [id]: unknown id must start with u-")
    if kind == "hypothesis" and not record_id.startswith("h-"):
        errors.append(f"{path.relative_to(ROOT)} [id]: hypothesis id must start with h-")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Promote Wave Factory staged batch")
    parser.add_argument(
        "--stage",
        default=str(DEFAULT_STAGE.relative_to(ROOT)),
        help="Staging root generated by wave_factory.py",
    )
    parser.add_argument("--apply", action="store_true", help="Actually move files into canonical folders")
    args = parser.parse_args()

    stage_root = (ROOT / args.stage).resolve()
    if not stage_root.exists():
        print(f"[promote-wave-factory] Stage directory not found: {stage_root}")
        return 1

    validators = build_validators()
    stage_sets = {
        "bridge": sorted((stage_root / "cross-domain").rglob("b-*.yaml")),
        "unknown": sorted((stage_root / "unknowns-catalog").rglob("u-*.yaml")),
        "hypothesis": sorted((stage_root / "hypotheses" / "active").rglob("h-*.yaml")),
    }

    total_staged = sum(len(paths) for paths in stage_sets.values())
    if total_staged == 0:
        print("[promote-wave-factory] No staged files found.")
        return 0

    all_errors: list[str] = []
    for kind, paths in stage_sets.items():
        for path in paths:
            all_errors.extend(validate_file(path, kind, validators[kind]))
    if all_errors:
        print("[promote-wave-factory] Validation failed:")
        for err in all_errors:
            print(f"  - {err}")
        return 1

    plans: list[tuple[Path, Path]] = []
    collisions: list[str] = []
    for path in stage_sets["bridge"]:
        rel = path.relative_to(stage_root / "cross-domain")
        target = ROOT / "cross-domain" / rel
        plans.append((path, target))
    for path in stage_sets["unknown"]:
        rel = path.relative_to(stage_root / "unknowns-catalog")
        target = ROOT / "unknowns-catalog" / rel
        plans.append((path, target))
    for path in stage_sets["hypothesis"]:
        rel = path.relative_to(stage_root / "hypotheses" / "active")
        target = ROOT / "hypotheses" / "active" / rel
        plans.append((path, target))

    for src, dst in plans:
        if dst.exists() and file_hash(src) != file_hash(dst):
            collisions.append(
                f"Collision with different content: {src.relative_to(ROOT)} -> {dst.relative_to(ROOT)}"
            )

    if collisions:
        print("[promote-wave-factory] Collision checks failed:")
        for collision in collisions:
            print(f"  - {collision}")
        return 1

    print(
        "[promote-wave-factory] Validation OK. Planned promotions: "
        f"bridges={len(stage_sets['bridge'])}, unknowns={len(stage_sets['unknown'])}, "
        f"hypotheses={len(stage_sets['hypothesis'])}"
    )
    if not args.apply:
        print("[promote-wave-factory] Dry-run only. Use --apply to move files.")
        return 0

    moved = 0
    skipped_identical = 0
    for src, dst in plans:
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists():
            skipped_identical += 1
            src.unlink()
            continue
        shutil.move(str(src), str(dst))
        moved += 1

    print(f"[promote-wave-factory] Applied. Moved={moved}, skipped_identical={skipped_identical}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
